theme: jekyll-theme-architect
<a href="http://phoenixgirl18.github.io/China-sMedia-/"> Information </a>
<html>
	<head>
		<title>China</title>
	</head>
	<body>
		<h1>China does not deserve free media!!</h1>
		<p>The chinese do not need free media, because of how crazy their system is in government. Plus, they have been<br/>
		controling Tibet and their culture that should't offend China at all. I believe Tibet needs media that is free than China.</p>
		<img src="https://i.ytimg.com/vi/dJ0WVNrdWU0/maxresdefault.jpg"height="160px"width="150px"/>
	</body>
</html>
